# Variables: Possible values
# 1. ENV: [dev, prod]
#    - Use for setting system environment
#    - default value: development

services:
  postgres:
    container_name: next_gen_job_hunting_postgres_db
    build:
      context: ./database/backend
      dockerfile: dockerfile
    volumes:
      - next_gen_job_hunting_data:/data/next_gen_job_hunting_postgres
    # restart: unless-stopped
    environment:
      PGDATA: "/data/next_gen_job_hunting_postgres"
    env_file:
      # use .env file as per Environment
      # Possible Values: [dev, pro]
      - ../.env
    ports:
      - "${DB_PORT:-5432}:5432"

  crawler_database:
    container_name: crawler_database
    build:
      context: ./database/crawler
      dockerfile: dockerfile
    volumes:
      - crawler_database_data:/data/crawler_database
    # restart: unless-stopped
    environment:
      PGDATA: "/data/crawler_database"
    env_file:
      # use .env file as per Environment
      # Possible Values: [dev, pro]
      - ../.env
    ports:
      - "${CRAWLER_DB_PORT:-5433}:5432"

volumes:
  next_gen_job_hunting_data:
  crawler_database_data:
