// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"next-gen-job-hunting/api/user"
	"next-gen-job-hunting/config/database"
)

// Injectors from wire.go:

func InitializeUserController() *user.UserController {
	db := database.NewDB()
	userRepository := user.NewUserRepository(db)
	userService := user.NewUserService(userRepository)
	userController := user.NewUserController(userService)
	return userController
}
